### PR TITLE
Update copyright text

### PR DESCRIPTION
**Pull request by Tanwi5**

### CODE REVIEW

**Comment by MingyeWu** [comment]
I think the copyright text should be:
# Copyright 2024, GE HealthCare. All rights reserved. See https://github.com/xcist/main/tree/master/license

**Comment by jjobin** [comment]
Legal told us that the correct legal entity name is GE Precision HealthCare and to use that.

**Review by jjobin — APPROVED** [review]

**Comment by MingyeWu** [comment]
But the license link is incorrect.

**Review by jjobin — APPROVED** [review]
Looks good.

**Pull request merged**
